name: Run Withings Sync

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run withings-sync
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        TRAINERROAD_USERNAME: ${{ secrets.TRAINERROAD_USERNAME }}
        TRAINERROAD_PASSWORD: ${{ secrets.TRAINERROAD_PASSWORD }}
      run: python withings_sync.py
